version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master
    - dev

test: off

environment:
  COVERALLS_API_TOKEN:
    secure: o/zOr1v66spV325X2294x5SR3o+ZLJkPbAsLNtBb3ZpU77uRzxCd7IMOAGwXELiQ

build_script:
- ps: ./build.ps1

artifacts:
- path: artifacts/*.nupkg
